document.write("<"+"SCRIPT LANGUAGE=\"JavaScript\">\n");
document.write("ord=Math.random();\n");
document.write("ord=ord*10000000000000000000;\n");
document.write("document.write('<"+"IFRAME SRC=\"http://ad.doubleclick.net/adi/DaniWeb.GSIAN/B12345;sz=336x280;ord='+ord+'?\" WIDTH=\"336\" HEIGHT=\"280\" MARGINWIDTH=\"0\" MARGINHEIGHT=\"0\" HSPACE=\"0\" VSPACE=\"0\" FRAMEBORDER=\"0\" SCROLLING=no BORDERCOLOR=\"#000000\">');\n");
document.write("if (navigator.userAgent.indexOf(\"Gecko\")==-1)\n");
document.write("{document.write('<"+"SCR' + 'IPT LANGUAGE=\"JavaScript\" SRC=\"http://ad.doubleclick.net/adj/DaniWeb.GSIAN/B12345;sz=336x280;abr=!ie;abr=!nn6;ord='+ord+'?\"><"+"\\/SCR' + 'IPT>');\n");
document.write("}\n");
document.write("document.write('<"+"/IFRAME>');\n");
document.write("<"+"/SCRIPT>\n");
document.write("<"+"NOSCRIPT>\n");
document.write("<"+"A HREF=\"http://ad.doubleclick.net/jump/DaniWeb.GSIAN/B12345;sz=336x280;ord=123456789?\" TARGET=\"_blank\">\n");
document.write("<"+"IMG SRC=\"http://ad.doubleclick.net/ad/DaniWeb.GSIAN/B12345;sz=336x280;ord=123456789?\" WIDTH=\"336\" HEIGHT=\"280\" BORDER=\"0\" ALT=\"Click here...\"><"+"/A>\n");
document.write("<"+"/NOSCRIPT>");
